# Generated by Django 4.0.5 on 2022-06-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbour',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
